version: "3"
services:
  db:
    image: mongo
    container_name: db_mongo
    volumes:
      - mongodata:/data/db
    ports:
      - "27017:27017"
  nextjs:
    depends_on:
      - db
    build: frontend
    ports:
      - "3000:3000"
volumes:
  mongodata:
