version: "3"
services:
  nextjs:
    network_mode: "host"
    build: frontend
    env_file:
      - frontend/.env

  pyrtmp:
    network_mode: "host"
    build: "pyth"
    env_file:
      - frontend/.env
    tmpfs:
      - /tmp/me