import Head from 'next/head';
import io from 'socket.io-client';
import { Box, Heading, VStack, Button } from '@chakra-ui/react';
import { useEffect, useState } from 'react';
import { signIn } from 'next-auth/react';
import FeatureGrid from '../components/FeatureGrid';

export default function Home() {
    const backendURL = process.env.NEXT_PUBLIC_BACKEND;

    return (
        <Box>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <VStack
                justifyContent={'center'}
                alignItems={'center'}
                minH={'100vh'}
                bg={'pink.050'}
                color={"#0A2540"}>
                <Button onClick={() => signIn('google')}
                    height='48px'
                    borderRadius='6px'
                    boxShadow={'rgba(45, 35, 66, .4) 0 2px 4px,rgba(45, 35, 66, .3) 0 7px 13px -3px,rgba(58, 65, 111, .5) 0 -3px 0 inset'}
                    transition={'box-shadow .15s,transform .15s'}
                    bgGradient='linear(to-bl, pink.100, pink.500)'
                    _hover={{
                        bgGradient: 'linear(to-br, pink.100, pink.500)',
                        boxShadow: 'rgba(45, 35, 66, .4) 0 4px 8px, rgba(45, 35, 66, .3) 0 7px 13px -3px, #3c4fe0 0 -3px 0 inset'
                    }}>
                    Sign in with YouTube
                </Button>
                <FeatureGrid />
            </VStack>
        </Box>
    );
}
