import Head from 'next/head';
import io from 'socket.io-client';
import { Box, Heading, VStack, Button } from '@chakra-ui/react';
import { useEffect, useState } from 'react';
import { signIn } from 'next-auth/react';
import FeatureGrid from '../components/FeatureGrid';

export default function Home() {
    const backendURL = process.env.NEXT_PUBLIC_BACKEND;

    return (
        <Box>
            <Head>
                <title>Create Next App</title>
                <meta
                    name='description'
                    content='Generated by create next app'
                />
                <link rel='icon' href='/favicon.ico' />
            </Head>

            <VStack
                justifyContent={'center'}
                alignItems={'center'}
                minH={'100vh'}
                bg={'pink.050'}
                color={"#0A2540"}>
                <Button onClick={() => signIn('google')}
                    height='48px'
                    border-radius='6px'
                    bgGradient='linear(to-bl, pink.100, pink.500)'
                    _hover={{
                        bgGradient: 'linear(to-tr, pink.100, pink.500)'
                    }}>
                    Sign in with YouTube
                </Button>
                <FeatureGrid />
            </VStack>
        </Box>
    );
}
